### ISSUE TITLE
apb install failed with pip install

### ISSUE THREAD

**Issue by chengzhang1016** [fusor/ansible-playbook-bundle#116] opened 2017-09-22 06:38 UTC
[root@host-8-241-60 pip-1.5.4]# python --version
    Python 2.7.5
     
    [root@host-8-241-60 pip-1.5.4]# pip --version
    pip 1.5.4 from /usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg (python 2.7)
     
    [root@host-8-241-60 pip-1.5.4]# pip install apb
    Downloading/unpacking apb
      Downloading apb-0.2.2.tar.gz
      Running setup.py (path:/tmp/pip_build_root/apb/setup.py) egg_info for package apb
       
        warning: no files found matching '*.txt'
        warning: no files found matching '*.txt' under directory 'docs'
    Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10,<4.0 in /usr/lib64/python2.7/site-packages (from apb)
    Downloading/unpacking docker>=2.1.0,<3.0.0 (from apb)
      Downloading docker-2.5.1-py2.py3-none-any.whl (111kB): 111kB downloaded
    Downloading/unpacking openshift>=0.0.1 (from apb)
      Downloading openshift-0.0.1-py2.py3-none-any.whl (1.6MB): 1.6MB downloaded
    Cleaning up...
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 278, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1265, in prepare_files
        req_to_install.extras):
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/pkg_resources.py", line 2232, in requires
        dm = self._dep_map
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/pkg_resources.py", line 2423, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/pkg_resources.py", line 2447, in _compute_dependencies
        parsed = next(parse_requirements(distvers))
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/pkg_resources.py", line 45, in <lambda>
        next = lambda o: o.next()
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements
        line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
      File "/usr/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/pkg_resources.py", line 2512, in scan_list
        raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
    ValueError: ('Expected version spec in', 'kubernetes ~=1.0.1', 'at', ' ~=1.0.1')
     
    Storing debug log for failure in /root/.pip/pip.log

**Comment by chengzhang1016** [comment] 2017-09-22 06:40
@jmrodri Could you help to confirm? Thanks.

**Comment by dymurray** [comment] 2017-09-25 15:11
@chengzhang1016 I can confirm this problem exists due to the kubernetes module changing versions and removing the 1.0.1 version from PyPi. I will work to fix this.

EDIT: Actually this was a red herring, it was just not showing up on PyPi. Ignore this comment.

**Comment by dymurray** [comment] 2017-09-25 15:22
@chengzhang1016 I think you need to update pip. My pip version is 9.0.1:
```
[dymurray@dymurray-desktop ansible-playbook-bundle]$ pip --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
```

It appears this error is from 1.5.4: https://pseudoscripter.wordpress.com/2016/12/20/pip-valueerror-expected-version-spec-in/

**Comment by rthallisey** [comment] 2017-10-04 17:35
Closing this bug since there hadn't been any update. If there's still an issue please reopen it.

**Closed as completed by rthallisey** 2017-10-04 17:35 UTC
